default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8_formatter_abspath==1.0.1
          - flake8-fixme==1.1.1
          - flake8-unused-arguments==0.0.6
          - flake8-use-fstring==1.1
          - wemake-python-styleguide==0.14.1

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8_formatter_abspath==1.0.1
          - flake8-fixme==1.1.1
          - flake8-unused-arguments==0.0.6
          - flake8-use-fstring==1.1
          - wemake-python-styleguide==0.14.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        entry: mypy
